language: java
install: true

jdk:
  - oraclejdk8

env:
  - CI=true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/5.4.1/
    - $HOME/.gradle/caches/modules-2/
    - $HOME/.gradle/wrapper/dists/